- hosts: master
  vars:
    fqdn: kdc.openampere.com
    password: ampere
    kdc_fqdn: kdc.openampere.com
    ipa_realm: OPENAMPERE.COM
    ipa_domain: openampere.com
  roles:
    - ipa-common
    - ipa-server