- hosts: node1
  vars:
    hostname: node1
    fqdn: node1.test.openampere.com
    password: openampere
    kdc_fqdn: kdc.test.openampere.com
    ipa_realm: TEST.OPENAMPERE.COM
    ipa_domain: test.openampere.com
  roles:
    - ipa-common
    - ipa-client
    - cdh-common
    - cdh-zookeeper
    - cdh-zk-kerberos